INFO 2025-02-16 09:40:02,304 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:40:02,452 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:40:02,452 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:40:02,452 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:40:02,452 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:40:02,452 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
INFO 2025-02-16 09:40:03,707 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:40:03,849 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:40:03,849 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:40:03,849 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:40:03,849 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:40:03,849 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
INFO 2025-02-16 09:40:45,414 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:40:45,557 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:40:45,557 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:40:45,558 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:40:45,558 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:40:45,558 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
ERROR 2025-02-16 09:41:32,163 [log - log_response:248] Internal Server Error: /xrpl/create-account-offer/
Traceback (most recent call last):
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\pythonProject\XRP_WebApp\xrpl_backend\xrpl_api\views.py", line 1188, in get
    signed_tx = await autofill_and_sign(tx, client, Wallet(wallet_address, None))
                                                    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xrpl\wallet\main.py", line 116, in __init__
    else derive_classic_address(self.public_key)
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xrpl\core\keypairs\main.py", line 97, in derive_classic_address
    account_id = get_account_id(bytes.fromhex(public_key))
                                ~~~~~~~~~~~~~^^^^^^^^^^^^
ValueError: non-hexadecimal number found in fromhex() arg at position 0
ERROR 2025-02-16 09:41:32,175 [basehttp - log_message:213] "GET /xrpl/create-account-offer/?wallet_address=r4ocA7HYdBXuvQPe1Dd7XUncZu8CT1QzkK&currency=TST&value=25 HTTP/1.1" 500 123188
INFO 2025-02-16 09:49:14,210 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:49:15,109 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:49:15,110 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:49:15,112 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:49:15,113 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:49:15,114 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
INFO 2025-02-16 09:49:16,623 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:49:16,776 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:49:16,776 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:49:16,776 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:49:16,776 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:49:16,776 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
INFO 2025-02-16 09:49:52,534 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:49:52,679 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:49:52,679 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:49:52,679 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:49:52,679 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:49:52,679 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
INFO 2025-02-16 09:50:11,118 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:50:11,166 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:50:11,166 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:50:11,166 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:50:11,166 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:50:11,166 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
INFO 2025-02-16 09:50:11,596 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:50:11,644 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:50:11,644 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:50:11,644 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:50:11,644 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:50:11,644 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
ERROR 2025-02-16 09:50:25,187 [log - log_response:248] Internal Server Error: /xrpl/create-account-offer/
Traceback (most recent call last):
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\pythonProject\XRP_WebApp\xrpl_backend\xrpl_api\views.py", line 1176, in get
    signed_tx = await autofill_and_sign(tx, client, Wallet(wallet_address, None))
                                                    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xrpl\wallet\main.py", line 116, in __init__
    else derive_classic_address(self.public_key)
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xrpl\core\keypairs\main.py", line 97, in derive_classic_address
    account_id = get_account_id(bytes.fromhex(public_key))
                                ~~~~~~~~~~~~~^^^^^^^^^^^^
ValueError: non-hexadecimal number found in fromhex() arg at position 0
ERROR 2025-02-16 09:50:25,190 [basehttp - log_message:213] "GET /xrpl/create-account-offer/?wallet_address=r4ocA7HYdBXuvQPe1Dd7XUncZu8CT1QzkK&currency=TST&value=25 HTTP/1.1" 500 91382
INFO 2025-02-16 09:53:03,040 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:53:03,087 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:53:03,087 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:53:03,087 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:53:03,087 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:53:03,087 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
INFO 2025-02-16 09:53:59,575 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:54:00,483 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:54:00,485 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:54:00,486 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:54:00,487 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:54:00,489 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
INFO 2025-02-16 09:54:02,000 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:54:02,150 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:54:02,150 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:54:02,150 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:54:02,151 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:54:02,151 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
ERROR 2025-02-16 09:54:31,484 [log - log_response:248] Internal Server Error: /xrpl/create-account-offer/
Traceback (most recent call last):
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\pythonProject\XRP_WebApp\xrpl_backend\xrpl_api\views.py", line 1182, in get
    result = await submit_and_wait(signed_tx, client)
                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xrpl\transaction\reliable_submission.py", line 47, in submit_and_wait
    return asyncio.run(
           ~~~~~~~~~~~^
        async_submit_and_wait(
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        )
        ^
    )
    ^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 191, in run
    raise RuntimeError(
        "asyncio.run() cannot be called from a running event loop")
RuntimeError: asyncio.run() cannot be called from a running event loop
ERROR 2025-02-16 09:54:31,560 [basehttp - log_message:213] "GET /xrpl/create-account-offer/?wallet_address=r4ocA7HYdBXuvQPe1Dd7XUncZu8CT1QzkK&currency=TST&value=25&sender_seed=sEdS82hNoMmkM7GottuGAFVecYTxRPH HTTP/1.1" 500 119882
INFO 2025-02-16 09:54:46,013 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:54:46,059 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:54:46,059 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:54:46,059 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:54:46,059 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:54:46,059 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
INFO 2025-02-16 09:54:46,486 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:54:46,530 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:54:46,531 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:54:46,531 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:54:46,531 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:54:46,531 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
ERROR 2025-02-16 09:54:50,858 [log - log_response:248] Internal Server Error: /xrpl/create-account-offer/
Traceback (most recent call last):
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\pythonProject\XRP_WebApp\xrpl_backend\xrpl_api\views.py", line 1182, in get
    result = await submit_and_wait(signed_tx, client)
                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xrpl\transaction\reliable_submission.py", line 47, in submit_and_wait
    return asyncio.run(
           ~~~~~~~~~~~^
        async_submit_and_wait(
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        )
        ^
    )
    ^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 191, in run
    raise RuntimeError(
        "asyncio.run() cannot be called from a running event loop")
RuntimeError: asyncio.run() cannot be called from a running event loop
ERROR 2025-02-16 09:54:50,863 [basehttp - log_message:213] "GET /xrpl/create-account-offer/?wallet_address=r4ocA7HYdBXuvQPe1Dd7XUncZu8CT1QzkK&currency=TST&value=25&sender_seed=sEdS82hNoMmkM7GottuGAFVecYTxRPH HTTP/1.1" 500 93945
INFO 2025-02-16 09:57:33,316 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:57:34,212 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:57:34,213 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:57:34,214 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:57:34,216 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:57:34,217 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
INFO 2025-02-16 09:57:35,720 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:57:35,869 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:57:35,870 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:57:35,870 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:57:35,870 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:57:35,870 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
ERROR 2025-02-16 09:57:44,350 [log - log_response:248] Internal Server Error: /xrpl/create-account-offer/
Traceback (most recent call last):
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\pythonProject\XRP_WebApp\xrpl_backend\xrpl_api\views.py", line 1182, in get
    result = await process_offer()
                   ~~~~~~~~~~~~~^^
TypeError: process_offer() missing 2 required positional arguments: 'signed_tx' and 'client'
ERROR 2025-02-16 09:57:44,361 [basehttp - log_message:213] "GET /xrpl/create-account-offer/?wallet_address=r4ocA7HYdBXuvQPe1Dd7XUncZu8CT1QzkK&currency=TST&value=25&sender_seed=sEdS82hNoMmkM7GottuGAFVecYTxRPH HTTP/1.1" 500 110135
INFO 2025-02-16 09:58:02,197 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:58:02,347 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:58:02,348 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:58:02,348 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:58:02,348 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:58:02,348 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
ERROR 2025-02-16 09:59:16,208 [log - log_response:248] Internal Server Error: /xrpl/create-account-offer/
Traceback (most recent call last):
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\asgiref\sync.py", line 254, in __call__
    return call_result.result()
           ~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\asgiref\sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\pythonProject\XRP_WebApp\xrpl_backend\xrpl_api\views.py", line 1182, in get
    result = await process_offer(signed_tx, client)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\app\pythonProject\XRP_WebApp\xrpl_backend\xrpl_api\utils.py", line 116, in process_offer
    result = await submit_and_wait(signed_tx, client)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xrpl\asyncio\transaction\reliable_submission.py", line 209, in submit_and_wait
    return await _send_reliable_submission(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        signed_transaction, client, fail_hard=fail_hard
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xrpl\asyncio\transaction\reliable_submission.py", line 116, in _send_reliable_submission
    return await _wait_for_final_transaction_outcome(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        transaction_hash, client, prelim_result, transaction.last_ledger_sequence
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xrpl\asyncio\transaction\reliable_submission.py", line 72, in _wait_for_final_transaction_outcome
    return await _wait_for_final_transaction_outcome(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        transaction_hash, client, prelim_result, last_ledger_sequence
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xrpl\asyncio\transaction\reliable_submission.py", line 72, in _wait_for_final_transaction_outcome
    return await _wait_for_final_transaction_outcome(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        transaction_hash, client, prelim_result, last_ledger_sequence
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xrpl\asyncio\transaction\reliable_submission.py", line 72, in _wait_for_final_transaction_outcome
    return await _wait_for_final_transaction_outcome(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        transaction_hash, client, prelim_result, last_ledger_sequence
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  [Previous line repeated 48 more times]
  File "C:\Users\bstra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xrpl\asyncio\transaction\reliable_submission.py", line 43, in _wait_for_final_transaction_outcome
    raise XRPLReliableSubmissionException(
    ...<3 lines>...
    )
xrpl.asyncio.transaction.reliable_submission.XRPLReliableSubmissionException: The latest validated ledger sequence 4899270 is greater than LastLedgerSequence 4899270 in the transaction. Prelim result: tefBAD_AUTH
ERROR 2025-02-16 09:59:16,233 [basehttp - log_message:213] "GET /xrpl/create-account-offer/?wallet_address=r4ocA7HYdBXuvQPe1Dd7XUncZu8CT1QzkK&currency=TST&value=25&sender_seed=sEdS82hNoMmkM7GottuGAFVecYTxRPH HTTP/1.1" 500 527747
INFO 2025-02-16 09:59:48,832 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 09:59:48,979 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 09:59:48,979 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 09:59:48,979 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 09:59:48,979 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 09:59:48,979 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
INFO 2025-02-16 10:04:10,502 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 10:04:10,551 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 10:04:10,551 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 10:04:10,551 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 10:04:10,551 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 10:04:10,551 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
INFO 2025-02-16 10:04:10,971 [apps - XrplApiConfig:17] ----------------- App started ----------------- 
INFO 2025-02-16 10:04:11,015 [apps - ready:39] Using XRP URL: https://s.altnet.rippletest.net:51234/
INFO 2025-02-16 10:04:11,015 [apps - ready:40] Using XRP FAUCET URL: https://faucet.altnet.rippletest.net/accounts
INFO 2025-02-16 10:04:11,015 [apps - ready:41] XRP_ACCOUNT_DELETE_FEE_IN_DROPS: 20
INFO 2025-02-16 10:04:11,015 [apps - ready:42] XRP_SEND_ACCOUNT_FEE_IN_DROPS: 20
INFO 2025-02-16 10:04:11,015 [apps - ready:43] BLACK_HOLE_ADDRESS: rrrrrrrrrrrrrrrrrrrrBZbvji
